### PR TITLE
Add CSP rules

### LINKED ISSUE #274: Add CSP Tauri rules
Using default CSP rules, page load fails because of
image

We need to add a `worker-src` drirective in tauri.conf.json csp
```
"csp": "default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self' worker-src 'self' blob:"
```
or
```
"csp": "default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self' worker-src blob:tauri://localhost/71d5375-d12a-49a6-8a24-27882f97900"

```

### PR DESCRIPTION
**Pull request by Janaka-Steph**
It fixes #274 

@filopedraz I readded the exact same CSP rules as before. For some reasons that I don't understand it is working now.

### CODE REVIEW

**Comment by filopedraz** [comment]
Did you test running `npm run build` ?

**Comment by Janaka-Steph** [comment]
Ha no only `npm run tauri dev`

**Comment by filopedraz** [comment]
`npm run tauri dev` doesn't fully run the desktop app.

**Comment by tiero** [comment]
Everytime app crashes in build but not in dev its due CSP rules

**Comment by jigneshsolanki** [comment]
@Janaka-Steph @filopedraz @tiero created pull request for this [302](https://github.com/premAI-io/prem-app/pull/302)

**Pull request closed without merging**
