### PR TITLE
243 new design for interaction buttons in service detail page

### PR DESCRIPTION
**Pull request by hardik-rl**

### CODE REVIEW

**Review by Janaka-Steph — COMMENTED** [review]
Restart is missing?
Start is missing also but clicking Open button will start the service, so the UX is unclear. @filopedraz

**Comment by itschetu** [comment]
@filopedraz  do we need the same as before and just change new UI or need to change text "open" to "start" ? and do we have restart functionality ?

**Comment by filopedraz** [comment]
Same as before and we don't have restart functionality for now. You can create an issue in prem-daemon about restart endpoint

**Comment by Janaka-Steph** [comment]
@hardik-rl Please rebase

**Comment by hardik-rl** [comment]
### @Janaka-Steph conflict is resolved,
please check it

**Review by Janaka-Steph — APPROVED** [review]

**Comment by Janaka-Steph** [comment]
@hardik-rl there is still an conflict

**Pull request closed without merging**
