### PR TITLE
add worker src rule in csp

### LINKED ISSUE #274: Add CSP Tauri rules
Using default CSP rules, page load fails because of
image

We need to add a `worker-src` drirective in tauri.conf.json csp
```
"csp": "default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self' worker-src 'self' blob:"
```
or
```
"csp": "default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self' worker-src blob:tauri://localhost/71d5375-d12a-49a6-8a24-27882f97900"

```

### PR DESCRIPTION
**Pull request by jigneshsolanki**
Fixes #274

### CODE REVIEW

**Comment by Janaka-Steph** [comment]
@jigneshsolanki A semicolon is missing at the end the `default-src` directive.

**Comment by jigneshsolanki** [comment]
@Janaka-Steph not sure where. I just used your changes and put `worker-src` at the end.

**Comment by Janaka-Steph** [comment]
Like this `"default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self'; img-src: 'self'; worker-src blob:;"`
Did you tested it with `npm run build`?

**Comment by jigneshsolanki** [comment]
@Janaka-Steph Yes, I have already tested with `npm run tauri build`

**Pull request closed without merging**
