### PR TITLE
add: handle edge cases & tests for macos

### PR DESCRIPTION
**Pull request by swarnimarun**
Tests currently would only run on macos, but since we don't have a CI it shouldn't be an issue, when we add a CI we should support linux and other platforms as well for these tests.

### CODE REVIEW

**Comment by swarnimarun** [comment]
@biswaroop1547 r?

**Comment by biswaroop1547** [comment]
lgtm! also works for previously failing case i.e:
```
{"aarch64-apple-darwin": None, "universal-apple-darwin": Some("xyz.com"), "x86_64-apple-darwin": None}
```

**Review by biswaroop1547 — APPROVED** [review]

**Comment by swarnimarun** [comment]
@tiero merge?

**Comment by tiero** [comment]
utACK https://github.com/premAI-io/prem-app/pull/477/commits/65b7ebf91d008253e8cf94fff1f4918ef19ab4e2

**Pull request merged**
