### PR TITLE
feat: is_offline command & handle reload and offline

### PR DESCRIPTION
**Pull request by swarnimarun**
Fixes https://github.com/premAI-io/prem-app/issues/476

### CODE REVIEW

**Comment by tiero** [comment]
Shall we add also a Tauri event so we can attach a listener on JS side instead of polling is offline command?

**Comment by swarnimarun** [comment]
That works as well but the question is when should we emit this event?

**Comment by swarnimarun** [comment]
Should we just emit is_offline if the load of service manifest fails, if we are just emitting once I think `is_offline` is better.

**Comment by Janaka-Steph** [comment]
This PR conflicts with Registry PR in setup hook

**Comment by tiero** [comment]
> That works as well but the question is when should we emit this event?

didn't checked the code yet, but I assume we should continuously monitor the state of the internet no? so when state changes (from online to offline or viceversa) we should emit the event

**Comment by swarnimarun** [comment]
closing will redo in a separate PR, rebasing is a lot more annoying than expected.

**Pull request closed without merging**
