### PR TITLE
fix: stable beluga as a petals service process not stopping

### PR DESCRIPTION
**Pull request by biswaroop1547**
use SIGKILL as failsafe when SIGTERM doesn't exit process.

### CODE REVIEW

**Comment by biswaroop1547** [comment]
@swarnimarun @Janaka-Steph review please 🙏🏻

**Comment by Janaka-Steph** [comment]
p2pd process is still not killed

**Comment by Janaka-Steph** [comment]
Killing by name works, even though I get error message `pkill: signalling pid 30017: Operation not permitted`

```
    let process_name = "p2pd";
    if let Err(err) = Command::new("pkill").arg(process_name).spawn() {
        eprintln!("Failed to kill process {}: {}", process_name, err);
    }
```

The `setup-petals.sh` script could assign a more specific name to this process to distinguish it from Swarm processes.

**Comment by biswaroop1547** [comment]
@Janaka-Steph this PR doesn't take care of #511 currently due to [this](https://github.com/premAI-io/prem-app/issues/511#issuecomment-1805319024) issue

**Comment by biswaroop1547** [comment]
> The setup-petals.sh script could assign a more specific name to this process to distinguish it from Swarm processes.
But this process gets started internally and setup-petals.sh doesn't have access to this process right after creation, are you suggesting maybe we can rename this process to be something right after setup-petals.sh script starts the petals server so that it could be found easily?

**Comment by Janaka-Steph** [comment]
But which issue are we trying to solve here then?
On `main`, process `python3.1` is killed, `p2pd` is not but it's an other issue. I don't have any other processes running.

**Comment by biswaroop1547** [comment]
it does seem to end the process but this spinner never resolves for me, which is happening due to a race condition if I understand correctly, hence I added `drop` statements in my PR, so using that it works and it doesn't hang on this spinner state
image

Also here if `SIGTERM` doesn't work incase then `SIGKILL` will be sent for ending the process.

**Comment by biswaroop1547** [comment]
closing this PR, since after using the latest commit from main branch, and having a clean local state the stopping issue isn't happening anymore. Thanks for the help 🙏🏻

**Pull request closed without merging**
