### PR TITLE
Fix download progress

### PR DESCRIPTION
**Pull request by Janaka-Steph**
It fixes https://github.com/premAI-io/prem-app/issues/255
It fixes https://github.com/premAI-io/prem-app/issues/248

The idea is to call download function when Service page (Home) is mounting with any ServiceId that is in progress.

@tiero @filopedraz

### CODE REVIEW

**Comment by tiero** [comment]
cant test unfrotunately for my bug with prem-daemon not being started. Not sure why it's happenign only to me :(

**Comment by tiero** [comment]
@filopedraz can you test this branch with `cargo tauri dev`?

**Comment by filopedraz** [comment]
Don't think it's related to these changes, but it doesn't run anymore `premd` on start. Even if I click on `Check Again`.

image

**Comment by filopedraz** [comment]
@Janaka-Steph @tiero we should create an issue for what concerns `premd` not starting. @Janaka-Steph I tested the download and it looks very nice now.

**Review by filopedraz — APPROVED** [review]

**Pull request merged**
