### PR TITLE
Display swarm info + style

### LINKED ISSUE #448: Improve Prem Network Setting's UI
I would also show the Server ID and the model along with number of block when we are running

image

_Originally posted by @tiero in https://github.com/premAI-io/prem-app/issues/440#issuecomment-1785181343_

### PR DESCRIPTION
**Pull request by Janaka-Steph**
It closes #448 

I also changed the layout which I find a bit cleaner.
Screenshot 2023-10-30 at 19 20 01
Screenshot 2023-10-30 at 19 21 00

### CODE REVIEW

**Comment by filopedraz** [comment]
@Janaka-Steph I would add the link to the explorer somewhere too with the model you are contributing too e.g., https://network.premai.io/model/StableBeluga2 CC @tiero?

**Comment by tiero** [comment]
> @Janaka-Steph I would add the link to the explorer somewhere too with the model you are contributing too e.g., https://network.premai.io/model/StableBeluga2 CC @tiero?

Yes but I suggest standardizing the URI path of the explorer to match the full model id `petals-team/StableBeluga2` in the URL path, so then we can do `https://network.premai.io/model/{swarmInfo.model}`

**Comment by filopedraz** [comment]
Makes sense.

**Comment by Janaka-Steph** [comment]
Can we merge this for now?

**Pull request merged**
