### PR TITLE
display actual error message in chat

### PR DESCRIPTION
**Pull request by jigneshsolanki**

### CODE REVIEW

**Comment by filippopedrazzinifp** [comment]
@jigneshsolanki I suggest we do: `Something went worng: {error}`

**Comment by filippopedrazzinifp** [comment]
@jigneshsolanki conflicts

**Comment by jigneshsolanki** [comment]
> @jigneshsolanki I suggest we do: `Something went worng: {error}`

Done

**Comment by jigneshsolanki** [comment]
> @jigneshsolanki conflicts

Conflicts resolved

**Pull request merged**
